# Generated by Django 4.2.5 on 2023-09-26 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendor_user'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vendor',
            managers=[
            ],
        ),
    ]
