# Generated by Django 4.2.5 on 2023-09-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userprofile_image'),
        ('vendors', '0006_alter_vendor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='account.user'),
        ),
    ]
